#!/bin/sh

bash ~/.fehbg
picom --backend xrender --vsync --fade-in-step=1 --fade-out-step=1 &
polybar &
sxhkd &
unclutter &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	0
bspc config window_gap          	16
bspc config top_padding 		30

bspc config split_ratio         	0.50
bspc config focus_follows_pointer   	true
